#REarrange the sentence

In [19]:
import numpy as np
name1='milk'
name2='butter'
qty1=2
qty2=4
print("i want "+ str(qty1)+name1+" and "+str(qty2)+name2)

i want 2milk and 4butter


##simple Example of numpy

In [20]:
import numpy as np
A=np.array([[1,2,3],[2,3,4]])
B=np.array([[3,4,5],[5,6,7]])
print(A*B)

[[ 3  8 15]
 [10 18 28]]


In [21]:
print(A-B)

[[-2 -2 -2]
 [-3 -3 -3]]


In [22]:
print(A%B)

[[1 2 3]
 [2 3 4]]


In [23]:
print(A/B)

[[0.33333333 0.5        0.6       ]
 [0.4        0.5        0.57142857]]


In [24]:
print(np.std(A))

0.9574271077563381


In [25]:
print(np.std(B))

1.2909944487358056


In [26]:
print(A.ndim)

2


In [27]:
print(A.shape)

(2, 3)


In [28]:
print(B.shape)

(2, 3)


#printing Zeros and Ones in dim

In [29]:
D=np.ones([4,4])

In [30]:
print(D)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
F=np.zeros([4,4])
print(F)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Replacing specidfied number above matrices

In [32]:
g=np.array([[2,3,4],[4,5,6]])

In [33]:
print(g)

[[2 3 4]
 [4 5 6]]


In [34]:
g[1,2]=10

In [35]:
print(g)

[[ 2  3  4]
 [ 4  5 10]]


GIVING RANDOM VALUES ROWS AND COLUMNS

In [36]:
C=np.random.rand(4,5)
print(C)

[[0.90590468 0.98730875 0.11684046 0.62083466 0.19536806]
 [0.68826841 0.97932901 0.16272619 0.96381289 0.84477199]
 [0.87653084 0.89969742 0.69488088 0.99541931 0.12483468]
 [0.60049369 0.74801821 0.37546536 0.46206292 0.99385377]]


Arrange in numpy

In [37]:
D=np.arange(10,37,2)
print(D)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36]


Linspace

In [42]:
E=np.linspace(0,2,15)
print(E)

[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.         1.14285714 1.28571429 1.42857143 1.57142857
 1.71428571 1.85714286 2.        ]


Aggregation Functions

In [44]:
F=np.array([11,2,345,12,45,2,4])
print(F.max())

345


In [45]:
print(F.min())

2


In [46]:
print(F.sum())

421


In [47]:
print(F.mean())

60.142857142857146


In [50]:
g=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print(g)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [52]:
g[2:,1:3]

array([[8, 9]])

Regular Expressions manipulating

In [60]:
import re
A="this is a good day"
if re.search("good",A):
    print("fine")
else:
    print("well")

fine


In [65]:
firstname='molankuola'
lastname='Ram'
print(firstname+' '+lastname)

molankuolaRam


In [68]:
print(firstname * 3)

molankuolamolankuolamolankuola


In [69]:
print('molan' in firstname)

True


In [24]:
A='heyy this ram iT'.split(' ')[0]
B='hello mic how are you'.split(' ')[-1]

In [42]:
x={'ram' : 'ram.molankula.poorna@gmail.com','ganesh':'gani@gmaiul.com','fun':'fun@gmail.com'}
for emails in x.values():
    print(emails)

ram.molankula.poorna@gmail.com
fun@gmail.com
gani@gmaiul.com
fun@gmail.com
fun@gmail.com
fun@gmail.com


In [46]:
for name,emails in x.items():
    print(name)
    print(emails)

ram
ram.molankula.poorna@gmail.com
ganesh
gani@gmaiul.com
fun
fun@gmail.com


In [25]:
print(A)

heyy


In [26]:
print(B)

you


PANDAS

In [2]:
import pandas as pd
names=['ram','ganesh','shyam']
d=pd.Series(names)
print(d)

0       ram
1    ganesh
2     shyam
dtype: object


In [15]:
numbers=[111,12,13,165,16,7]
pd.Series(numbers)

0    111
1     12
2     13
3    165
4     16
5      7
dtype: int64

In [6]:
names=['ram','ganesh',None]
pd.Series(names)

0       ram
1    ganesh
2      None
dtype: object

In [42]:
import pandas as pd
record1=pd.Series({'name':'hello',
                  'class':'physics',
                   'score':90})
df=pd.DataFrame(record1)
print(df)


             0
name     hello
class  physics
score       90


In [43]:
record2=pd.Series({'name':'mic',
                  'class':'physics',
                   'score':99})
df=pd.DataFrame(record2)
print(df)

             0
name       mic
class  physics
score       99


In [44]:
df=pd.DataFrame([record1,record2],index=['school1','school2'])
print(df)

          name    class  score
school1  hello  physics     90
school2    mic  physics     99


In [56]:
employee={'numbers':[1,2,3,4,5],'names':['ram','ganesh','shyam','amma','nanna'],'score':[1,2,3,4,5]}
table=pd.DataFrame(employee)
print(table)

   numbers   names  score
0        1     ram      1
1        2  ganesh      2
2        3   shyam      3
3        4    amma      4
4        5   nanna      5


In [57]:
print(table.head(3))

   numbers   names  score
0        1     ram      1
1        2  ganesh      2
2        3   shyam      3


In [58]:
print(table.tail(3))

   numbers  names  score
2        3  shyam      3
3        4   amma      4
4        5  nanna      5


In [59]:
employee1={'numbers':[1,2,3,4,5],'names':['ram','ganesh','shyam','amma','nanna'],'score':[1,2,3,4,5]}
employee2={'numbers':[1,2,3,4,5],'names':['ram','ganesh','shyam','amma','nanna'],'score':[1,2,3,4,5]}

In [60]:
table1=pd.DataFrame(employee1)

In [61]:
print(table1)

   numbers   names  score
0        1     ram      1
1        2  ganesh      2
2        3   shyam      3
3        4    amma      4
4        5   nanna      5


In [62]:
table2=pd.DataFrame(employee2)
print(table2)

   numbers   names  score
0        1     ram      1
1        2  ganesh      2
2        3   shyam      3
3        4    amma      4
4        5   nanna      5


In [64]:
fusion=pd.merge(table1,table2)
print(fusion)

   numbers   names  score
0        1     ram      1
1        2  ganesh      2
2        3   shyam      3
3        4    amma      4
4        5   nanna      5


In [65]:
hai=pd.read_csv('C:\\Users\\user\\Desktop\\Data.csv')
print(hai)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [66]:
print(hai.head(3))

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
